### ISSUE TITLE
Duplicate ids generated for USB media

### ISSUE THREAD

**Issue by ianparkinson** [mjoblin/vibin#128]
When using USB media attached to the CXNv2, multiple tracks of the same album with the same title causes two issues:

1. Warnings in console on the tracks page: `react-dom.development.js:86 Warning: Encountered two children with the same key, id53. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`
2. Playing a track will instead play the first track with the same name on the album.

**Comment by mjoblin** [comment]
Nice fix!

Random note about releases: If you ever want a new release made, just let me know in any PR/issue. Either way, if enough time has passed then I'll make a new release regardless -- just so the latest is out there. But I'm happy to be told when you're at a point where you think a release is justified. The main win really comes on updates to the UI side, where a new release makes the updates visible to `vibin installui`.

And thanks again!
